# Generated by Django 4.2.16 on 2026-05-12 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('institution_type', models.CharField(choices=[('library', 'Библиотека'), ('museum', 'Музей'), ('theater', 'Театр'), ('culture_house', 'Дом культуры'), ('art_school', 'Школа искусств / ДМШ'), ('other', 'Иное')], default='other', max_length=20, verbose_name='Тип учреждения')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('head_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО руководителя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('total_limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общий лимит (руб.)')),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='institutions.institution', verbose_name='Учреждение')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Установил')),
            ],
            options={
                'verbose_name': 'Лимит финансирования',
                'verbose_name_plural': 'Лимиты финансирования',
                'unique_together': {('institution', 'year')},
            },
        ),
    ]
