# Generated by Django 4.2.16 on 2026-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KOSGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код КОСГУ')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'КОСГУ',
                'verbose_name_plural': 'КОСГУ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код КВР')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'КВР',
                'verbose_name_plural': 'КВР',
                'ordering': ['code'],
            },
        ),
    ]
