# Generated by Django 4.2.16 on 2026-05-12 11:32

import apps.budget_requests.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Год планирования')),
                ('period_type', models.CharField(choices=[('annual', 'Годовая'), ('quarterly', 'Квартальная')], default='annual', max_length=10, verbose_name='Тип периода')),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I кв.'), (2, 'II кв.'), (3, 'III кв.'), (4, 'IV кв.')], null=True, verbose_name='Квартал')),
                ('funding_type', models.CharField(choices=[('subsidy', 'Субсидия на выполнение задания'), ('paid', 'Платные услуги'), ('other', 'Иные цели')], default='subsidy', max_length=10, verbose_name='Тип средств')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На проверке в ЦБ'), ('returned', 'Возвращено на доработку'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('included', 'Включена в бюджет')], default='draft', max_length=10, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Заявленная сумма (руб.)')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Согласованная сумма (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий бухгалтера')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='institutions.institution', verbose_name='Учреждение')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Проверил бухгалтер')),
            ],
            options={
                'verbose_name': 'Бюджетная заявка',
                'verbose_name_plural': 'Бюджетные заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Детализация / Обоснование')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за ед. (руб.)')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Итого (руб.)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.budget_requests.models.attachment_upload_path, verbose_name='Файл-обоснование (скан/КП)')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('kosgu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classifiers.kosgu', verbose_name='КОСГУ')),
                ('kvr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classifiers.kvr', verbose_name='КВР')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget_requests.budgetrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Строка заявки',
                'verbose_name_plural': 'Строки заявки',
            },
        ),
        migrations.CreateModel(
            name='RequestLineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Было')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='budget_requests.requestline', verbose_name='Строка заявки')),
            ],
            options={
                'verbose_name': 'Лог изменения строки',
                'verbose_name_plural': 'Логи изменений строк',
                'ordering': ['-changed_at'],
            },
        ),
    ]
