# Generated by Django 4.2.16 on 2026-05-12 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('contractor', models.CharField(max_length=300, verbose_name='Контрагент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма договора (руб.)')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто (оплачено)'), ('cancelled', 'Отменено')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='institutions.institution', verbose_name='Учреждение')),
                ('kosgu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classifiers.kosgu', verbose_name='КОСГУ')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-contract_date'],
            },
        ),
        migrations.CreateModel(
            name='FactPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма (руб.)')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('description', models.CharField(max_length=500, verbose_name='Назначение платежа')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_payments', to='institutions.institution', verbose_name='Учреждение')),
                ('kosgu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classifiers.kosgu', verbose_name='КОСГУ')),
            ],
            options={
                'verbose_name': 'Кассовый расход',
                'verbose_name_plural': 'Кассовые расходы',
                'ordering': ['-payment_date'],
            },
        ),
    ]
